theme = "catppuccin_mocha"

[editor]
mouse = false
middle-click-paste = false
# shell = [ "fish", "-c" ]
line-number = "relative"
cursorline = true
completion-timeout = 5
completion-trigger-len = 1
true-color = true
undercurl = true
rulers = [ 100 ]
bufferline = "always"
color-modes = true
text-width = 100
trim-final-newlines = true
trim-trailing-whitespace = true
popup-border = "all"
clipboard-provider = "wayland"
end-of-line-diagnostics = "hint"

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.whitespace.render]
# space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.indent-guides]
render = true

[editor.gutters.line-numbers]
min-width = 1

[editor.smart-tab]
supersede-menu = true

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
S-tab = "move_parent_node_start"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

[keys.select]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
