[editor]
mouse = false
shell = [ "fish", "-c" ]
line-number = "relative"
cursorline = true
completion-timeout = 5
completion-trigger-len = 1
# completion-replace = true
true-color = true
undercurl = true
rulers = [ 100 ]
popup-border = "all"
clipboard-provider = "wayland"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.indent-guides]
render = true

[editor.gutters.line-numbers]
min-width = 1

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.select]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
