theme = "base16_transparent"

[editor]
mouse = false
middle-click-paste = false
shell = [ "fish", "-c" ]
line-number = "relative"
cursorline = true
completion-timeout = 5
completion-trigger-len = 1
true-color = true
undercurl = true
rulers = [ 100 ]
color-modes = true
text-width = 100
trim-final-newlines = true
trim-trailing-whitespace = true
popup-border = "all"
clipboard-provider = "wayland"
end-of-line-diagnostics = "hint"

[editor.statusline]
left = [
  "mode",
  "spacer",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator"
]

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.gutters.line-numbers]
min-width = 1

[editor.smart-tab]
supersede-menu = true

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
S-tab = "move_parent_node_start"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
ret = ":w"
S-ret = ":wa"

[keys.select]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
