[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
rulers = [ 80 ]
auto-format = true

[[language]]
name = "c"
auto-format = true

[[language]]
name = "rust"

[[language]]
name = "typst"
auto-format = true

[[language]]
name = "python"
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "go"
auto-format = true
rulers = [ 80 ]
formatter = { command = "goimports" }


[language-server.clangd.config]
args = [
  "--background-index-priority=normal",
  "--clang-tidy",
  "--completion-style=detailed",
  "--header-insertion-decorators",
  "--import-insertions",
  "--limit-references=0",
  "--limit-results=0",
  "--rename-file-limit=0",
  "--enable-config",
  "-j 4",
  "--malloc-trim",
  "--pch-storage=memory"
]

[language-server.rust-analyzer.config]
restartServerOnConfigChange = true
showSyntaxTree = true
testExplorer = true

[language-server.rust-analyzer.config.diagnostics]
previewRustcOutput = true
useRustcErrorCode = true
styleLints.enable = true

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.completion]
fullFunctionSignatures.enable = true
hideDeprecated = true
limit = "null"
postfix.enable = false
termSearch.enable = true

[language-server.rust-analyzer.config.hover]
actions.references.enable = true
maxSubstitutionLength = "null"
show.traitAssocItems = 5

[language-server.rust-analyzer.config.imports]
granularity.enforce = true
prefix = "crate"

[language-server.rust-analyzer.config.lens.references]
adt.enable = true
enumVariant.enable = true
method.enable = true
trait.enable = true

[language-server.rust-analyzer.config.references]
excludeImports = true
excludeTests = true

[language-server.rust-analyzer.config.semanticHighlighting]
operator.specialization.enable = true

[language-server.rust-analyzer.config.semanticHighlighting.punctuation]
enable = true
separate.macro.bang = true
specialization.enable = true

[language-server.tinymist.config]
# projectResolution = "lockDatabase"
# outputPath = "$root/target/$dir/$name"
# exportPdf = "onSave"
typstExtraArgs = [ "main.typ" ]
formatterMode = "typstyle"
formatterPrintWidth = 100
formatterIndentSize = 2
completion.triggerOnSnippetPlaceholders = true

[language-server.elm-language-server.config.elmLS]
elmReviewDiagnostics = "error"
disableElmLSDiagnostics = false
skipInstallPackageConfirmation = false
onlyUpdateDiagnosticsOnSave = false

[language-server.pylsp.config.pylsp.plugins.jedi_completion]
include_class_objects = true
include_function_objects = true
fuzzy = true
resolve_at_most = "null"

[language-server.pylsp.config.pylsp.plugins.pycodestyle]
maxLineLength = 100
indentSize = 4

[language-server.pylsp.config.pylsp.plugins.pydocstyle]
enabled = true
convention = "pep257"

[language-server.pylsp.config.pylsp.plugins.pylint]
enabled = true

[language-server.pylsp.config.pylsp.plugins.rope_autoimport]
enabled = true
memory = true

[language-server.pylsp.config.pylsp.signature]
formatter = "ruff"
